/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://rdh3rpg75zatdksyidi4yeqvzi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-alvdvkn2w5buzmkze7k2ddcfpa",
    "aws_cognito_identity_pool_id": "us-east-1:959e6d01-7b0c-4aae-ad2d-b745efc55dd0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_aLv5G97F3",
    "aws_user_pools_web_client_id": "6iu64v7sqvn9a9okd2jvniu31j",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
